insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (1, 'Den enskilde medborgaren', 171, 'Hebrew', 3, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (2, 'Best Intentions, The (Den goda viljan)', 100, 'Hebrew', 18, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (3, 'Fountain, The', 617, 'Spanish', 21, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (4, 'Always', 12, 'English', 26, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (5, 'Aamir', 295, 'English', 31, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (6, 'Until the End of the World (Bis ans Ende der Welt)', 524, 'Spanish', 22, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (7, 'Hansel & Gretel', 149, 'English', 1, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (8, 'Dude, Where''s My Car?', 227, 'Spanish', 13, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (9, 'Original Gangstas', 788, 'Russian', 29, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (10, 'Mutant Chronicles', 463, 'English', 31, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (11, 'Still Breathing', 39, 'Arabic', 17, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (12, 'Broadway Melody of 1940', 305, 'Spanish', 8, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (13, 'Pumpkinhead', 614, 'Hebrew', 17, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (14, 'Ladies in Lavender', 794, 'Russian', 25, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (15, 'GasLand', 550, 'English', 23, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (16, 'Holding, The', 229, 'English', 33, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (17, 'Jungle Book of Regulations, A (Nie Ma Rozy Bez Ognia)', 842, 'Yiddish', 20, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (18, 'Lotto Land', 698, 'English', 9, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (19, 'Lucky Star', 447, 'French', 5, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (20, 'Day of the Dead 2: Contagium', 461, 'Arabic', 5, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (21, 'Wrestling Ernest Hemingway', 363, 'Spanish', 33, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (22, 'Zatoichi the Outlaw (Zatôichi rôyaburi) (Zatôichi 16)', 287, 'Spanish', 14, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (23, 'Los Marziano', 968, 'Arabic', 5, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (24, 'Rock & Rule', 859, 'English', 21, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (25, 'Salaam Bombay!', 688, 'English', 2, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (26, 'The Hire: Powder Keg', 504, 'English', 5, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (27, 'In the City (En la ciudad)', 376, 'Arabic', 6, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (28, 'Saving Otter 501', 61, 'Arabic', 23, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (29, 'Melvin and Howard', 906, 'Spanish', 25, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (30, 'Malice', 663, 'Hebrew', 5, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (31, 'Vlad Tepes (Vlad &#354;epe&#351;)', 5, 'English', 33, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (32, 'Die! Die! My Darling! (Fanatic)', 114, 'Spanish', 10, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (33, 'Dragon Hunters (Chasseurs de dragons)', 176, 'Hebrew', 31, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (34, 'Sherlock Holmes', 25, 'Hebrew', 9, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (35, 'Stephanie Daley', 906, 'Hebrew', 15, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (36, 'Desperate Search', 751, 'French', 7, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (37, 'Lost in Space', 702, 'English', 19, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (38, 'Suture', 595, 'Yiddish', 5, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (39, '6954 Kilometriä Kotiin', 372, 'Hebrew', 1, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (40, 'Very Long Engagement, A (Un long dimanche de fiançailles)', 656, 'Arabic', 25, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (41, 'Spiderwick Chronicles, The', 903, 'Hebrew', 18, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (42, 'Ocean Heaven ', 167, 'Hebrew', 18, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (43, 'Blue', 496, 'Hebrew', 18, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (44, 'Ninja: Shadow of a Tear', 439, 'English', 25, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (45, 'Bohemian Eyes (Boheemi elää - Matti Pellonpää)', 612, 'Arabic', 5, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (46, 'Brother Rat', 506, 'French', 3, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (47, 'French Twist (Gazon maudit)', 522, 'Arabic', 28, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (48, 'Double Wedding', 95, 'Hebrew', 22, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (49, 'Tillie''s Punctured Romance', 945, 'Hebrew', 31, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (50, 'Manborg', 317, 'Russian', 14, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (51, 'Invisible Target (Naam yi boon sik)', 220, 'Russian', 11, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (52, '4 Little Girls', 579, 'English', 28, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (53, 'Fritz the Cat', 883, 'Arabic', 17, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (54, 'Hatari!', 822, 'English', 23, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (55, 'Steppenwolf', 709, 'English', 16, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (56, 'Get Thrashed: The Story of Thrash Metal', 654, 'Russian', 29, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (57, 'Nightmare Alley', 296, 'Arabic', 29, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (58, 'Yes Man', 332, 'Hebrew', 23, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (59, 'Bambou', 729, 'French', 16, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (60, 'Uwasa No Onna (The Woman in the Rumor) (Her Mother''s Profession)', 363, 'Arabic', 23, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (61, 'Happy Christmas', 117, 'French', 27, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (62, 'High Strung', 260, 'Hebrew', 23, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (63, 'Carol for Another Christmas', 793, 'Spanish', 8, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (64, 'Silent Action', 754, 'Spanish', 25, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (65, 'Viva', 462, 'Hebrew', 10, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (66, 'Raging Bull', 670, 'Spanish', 1, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (67, 'Great Day in the Morning', 55, 'Arabic', 31, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (68, 'Scarlet Clue, The (Charlie Chan in the Scarlet Clue)', 19, 'Russian', 15, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (69, 'Terminator 3: Rise of the Machines', 884, 'French', 1, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (70, 'A Lesson Before Dying', 580, 'English', 4, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (71, 'Salut cousin!', 788, 'Russian', 19, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (72, 'Glory Daze', 3, 'Yiddish', 17, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (73, 'No Man''s Land', 229, 'Yiddish', 4, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (74, 'Feel the Noise', 232, 'Yiddish', 26, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (75, 'Mannequin 2: On the Move', 71, 'Russian', 33, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (76, 'Fire and Ice', 442, 'Spanish', 7, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (77, 'Grave, The', 944, 'Russian', 3, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (78, 'Clerks', 908, 'Hebrew', 31, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (79, 'Krrish 3', 116, 'English', 27, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (80, 'Nightmare on Elm Street 5: The Dream Child, A', 111, 'Hebrew', 29, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (81, 'Sitcom', 442, 'Arabic', 33, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (82, 'First Comes Love', 615, 'French', 9, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (83, 'I Am Santa Claus', 981, 'Spanish', 2, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (84, 'Dating the Enemy', 957, 'English', 25, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (85, 'Jealousy', 617, 'Yiddish', 14, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (86, 'Watch on the Rhine', 12, 'English', 18, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (87, 'Puccini for Beginners', 419, 'Spanish', 27, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (88, 'Top Secret!', 710, 'Spanish', 7, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (89, 'Arizona Dream', 847, 'Spanish', 9, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (90, 'Call, The', 187, 'Arabic', 8, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (91, 'Honeymoon', 115, 'Russian', 17, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (92, 'Stars', 384, 'Russian', 25, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (93, 'Cool World', 271, 'French', 32, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (94, 'Resan Till Melonia', 530, 'Hebrew', 16, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (95, 'Sunshine', 131, 'Russian', 25, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (96, 'Genova (Summer in Genoa, A)', 126, 'Yiddish', 18, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (97, 'Slender Thread, The', 924, 'Arabic', 19, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (98, 'My Boyfriend''s Back', 854, 'Russian', 18, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (99, 'Trouble in Mind', 345, 'Arabic', 1, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (100, 'Forbidden City Cop (Dai lap mat tam 008)', 486, 'French', 21, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (101, 'Possession of David O''Reilly, The ', 199, 'English', 24, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (102, 'The Magnificent Gladiator', 97, 'French', 6, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (103, 'Dark Half, The', 107, 'Russian', 28, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (104, 'Ride with the Devil', 434, 'Russian', 13, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (105, 'Zero de conduite (Zero for Conduct) (Zéro de conduite: Jeunes diables au collège)', 49, 'English', 30, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (106, 'Redemption (Hummingbird)', 498, 'French', 12, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (107, 'Singles', 987, 'Spanish', 26, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (108, 'Honeymooners, The', 564, 'French', 14, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (109, '2 + 2 (Dos más dos)', 740, 'Arabic', 19, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (110, 'Secret Ceremony', 664, 'Hebrew', 1, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (111, 'Cargo', 941, 'Hebrew', 12, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (112, 'Final Option, The (Who Dares Wins)', 907, 'Yiddish', 1, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (113, 'Gods and Monsters', 613, 'Yiddish', 26, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (114, 'Harvest', 53, 'Hebrew', 23, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (115, 'Zero Years, The', 337, 'Arabic', 33, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (116, 'Gertie the Dinosaur', 13, 'Yiddish', 27, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (117, 'A Blank on the Map', 366, 'Yiddish', 18, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (118, 'Henry Kissinger: Secrets of a Superpower (Henry Kissinger - Geheimnisse einer Supermacht)', 902, 'Russian', 14, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (119, 'People, Places, Things', 816, 'Yiddish', 10, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (120, 'Ip Man: The Final Fight', 405, 'Hebrew', 24, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (121, 'Khumba', 960, 'Spanish', 21, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (122, 'Female Agents (Les femmes de l''ombre)', 671, 'Arabic', 24, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (123, 'The Fifth Season', 986, 'Hebrew', 26, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (124, 'Factotum', 53, 'French', 29, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (125, 'Bluebeard (Landru)', 18, 'Yiddish', 2, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (126, 'Braddock: Missing in Action III', 831, 'Yiddish', 26, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (127, 'Sita Sings the Blues', 125, 'Russian', 33, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (128, 'Darkest Hour, The', 96, 'Arabic', 31, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (129, 'Primal', 722, 'Yiddish', 25, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (130, 'George Lopez: Tall, Dark & Chicano', 137, 'Spanish', 26, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (131, 'Peter Pan', 395, 'Spanish', 30, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (132, 'Devil''s Carnival, The', 776, 'Arabic', 33, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (133, 'Just Cause', 194, 'Arabic', 25, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (134, 'Enemy Below, The', 839, 'Hebrew', 4, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (135, 'Nömadak TX', 256, 'Arabic', 7, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (136, 'Romeo and Juliet', 877, 'Yiddish', 28, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (137, 'The Oscar', 690, 'Arabic', 1, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (138, 'Parasite', 328, 'Russian', 29, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (139, 'Jesse Stone: Benefit of the Doubt', 650, 'Spanish', 17, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (140, 'Basara: Princess Goh', 152, 'French', 9, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (141, 'Collector, The', 458, 'Hebrew', 19, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (142, 'Rosa Luxemburg', 74, 'Spanish', 20, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (143, 'Fat City', 139, 'Spanish', 31, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (144, 'Experience, The (Tadjrebeh)', 725, 'English', 21, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (145, 'Total Recall', 493, 'Spanish', 21, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (146, 'One Day in September', 478, 'Arabic', 30, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (147, 'Earthquake', 929, 'Arabic', 3, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (148, 'Dead Tired (Grosse Fatigue)', 298, 'Russian', 29, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (149, 'Short Eyes', 195, 'Hebrew', 2, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (150, 'Mind Reader, The', 801, 'French', 21, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (151, 'Hunter, The', 826, 'Spanish', 9, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (152, 'Red Beret, The', 541, 'Hebrew', 32, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (153, 'Dead Man on Campus', 778, 'Yiddish', 3, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (154, 'Happythankyoumoreplease', 525, 'Yiddish', 25, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (155, 'Beyond the Lights', 411, 'Spanish', 33, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (156, 'No. 1 Ladies'' Detective Agency, The', 138, 'Russian', 5, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (157, 'Raincoat', 761, 'Arabic', 3, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (158, 'Welcome to Collinwood', 745, 'Hebrew', 21, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (159, 'Enemy of the State', 514, 'French', 28, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (160, 'Japon (a.k.a. Japan) (Japón)', 777, 'French', 30, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (161, 'Jackass 3.5', 287, 'Russian', 6, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (162, 'Under the Sand', 748, 'Hebrew', 15, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (163, 'The Bride Wore Red', 46, 'Hebrew', 12, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (164, 'Unfinished Song (Song for Marion)', 228, 'Hebrew', 15, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (165, 'The Incident', 272, 'Hebrew', 29, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (166, 'Gunga Din', 74, 'English', 12, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (167, 'Firewalker', 441, 'Hebrew', 11, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (168, 'Reconstituirea (Reconstruction)', 230, 'English', 13, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (169, 'Scarlet Empress, The', 947, 'Hebrew', 23, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (170, 'Numb', 496, 'Russian', 8, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (171, 'Achilles and the Tortoise (Akiresu to kame)', 656, 'Russian', 17, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (172, 'Trial of the Incredible Hulk, The', 747, 'Russian', 12, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (173, 'Exercice de l''État, L''', 185, 'Hebrew', 29, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (174, 'LEGO DC Comics Super Heroes: Justice League vs. Bizarro League', 878, 'French', 31, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (175, 'Blue Chips', 174, 'Arabic', 24, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (176, 'Mean Machine', 954, 'French', 11, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (177, 'Crude Oasis, The', 405, 'Spanish', 23, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (178, 'Let No Man Write My Epitaph', 612, 'Arabic', 28, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (179, 'Fraternity Demon', 602, 'Yiddish', 17, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (180, 'Nueba Yol', 570, 'Russian', 1, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (181, 'Nobody Owns Me (Mig äger ingen)', 990, 'English', 4, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (182, 'Black Friday', 421, 'French', 25, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (183, 'If I Want to Whistle, I Whistle (Eu cand vreau sa fluier, fluier)', 348, 'Hebrew', 1, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (184, 'Summer of ''42', 835, 'Yiddish', 5, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (185, 'Attila (Attila the Hun)', 575, 'Spanish', 30, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (186, 'Workingman''s Death', 489, 'French', 5, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (187, 'Far From Home: The Adventures of Yellow Dog', 180, 'English', 11, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (188, 'Sound of My Voice', 130, 'Yiddish', 5, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (189, 'Bill Cosby, Himself', 797, 'Russian', 11, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (190, 'Josie and the Pussycats', 224, 'French', 10, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (191, 'Hellraiser: Bloodline', 660, 'Arabic', 22, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (192, 'Money for Nothing', 268, 'Hebrew', 15, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (193, 'Man Who Sued God, The', 40, 'Arabic', 1, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (194, 'Sweet Nothing', 4, 'Hebrew', 14, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (195, 'Shinobi No Mono 3: Resurrection (Shin shinobi no mono)', 206, 'Yiddish', 30, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (196, 'All-Star Superman', 249, 'Arabic', 27, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (197, 'Dude, Where''s My Car?', 312, 'Arabic', 1, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (198, 'Jolly Boys'' Last Stand, The', 55, 'Spanish', 1, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (199, 'Miss Representation', 151, 'Russian', 31, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (200, 'Everyone''s Hero', 251, 'Spanish', 28, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (201, 'I Am a Sex Addict', 824, 'Hebrew', 27, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (202, 'Slappy and the Stinkers', 523, 'French', 28, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (203, 'Backflash (Backflash Blues)', 458, 'Russian', 29, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (204, 'Day of the Triffids, The', 239, 'French', 6, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (205, 'Man, Woman and the Wall (Kikareta onna no mirareta yoru)', 622, 'Russian', 15, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (206, 'Loaded Weapon 1 (National Lampoon''s Loaded Weapon 1)', 89, 'Arabic', 21, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (207, 'Addicted to Love', 713, 'Yiddish', 13, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (208, 'Extraction', 579, 'Arabic', 13, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (209, 'Locke', 548, 'Yiddish', 5, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (210, 'Carrie', 406, 'Russian', 32, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (211, 'Man Vanishes, A (Ningen Johatsu)', 713, 'Spanish', 27, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (212, 'Killing Room, The', 195, 'Spanish', 18, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (213, 'Khumba', 987, 'Yiddish', 27, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (214, 'Man in the Iron Mask, The', 396, 'Spanish', 14, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (215, 'ABCs of Death, The', 810, 'Russian', 4, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (216, 'Death at a Funeral', 986, 'Arabic', 20, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (217, 'Little World of Don Camillo, The (Petit monde de Don Camillo, Le)', 119, 'Hebrew', 10, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (218, 'Devil, Probably, The (Diable probablement, Le)', 704, 'Yiddish', 23, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (219, 'Dr. Jekyll and Mr. Hyde', 123, 'Hebrew', 11, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (220, 'Just Cause', 845, 'Hebrew', 23, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (221, 'Lord Love a Duck', 585, 'Hebrew', 6, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (222, 'Johnny 100 Pesos (Johnny cien pesos)', 641, 'Arabic', 20, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (223, 'Campfire Tales', 700, 'Hebrew', 15, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (224, 'Happy End', 547, 'French', 30, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (225, 'Journey of Natty Gann, The', 755, 'Hebrew', 19, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (226, 'New Best Friend', 258, 'Russian', 15, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (227, 'Dog Year, A', 347, 'Russian', 28, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (228, 'Animal House', 240, 'Spanish', 8, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (229, 'Pearl, The (La perla)', 643, 'Arabic', 28, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (230, 'Beverly Hills Cop III', 646, 'Yiddish', 6, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (231, 'Danika', 681, 'Arabic', 9, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (232, 'Cool World, The', 857, 'Spanish', 4, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (233, 'Still Alice', 200, 'Yiddish', 10, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (234, 'Tarzan''s New York Adventure', 841, 'Arabic', 5, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (235, 'Pope Joan (Die Päpstin)', 735, 'French', 29, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (236, 'Tatsumi', 920, 'Russian', 13, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (237, 'Burnt by the Sun 2 (Utomlyonnye solntsem 2)', 885, 'Spanish', 11, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (238, 'Lost and Delirious', 768, 'Hebrew', 29, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (239, 'Farewell, The (Abschied - Brechts letzter Sommer)', 743, 'Russian', 27, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (240, 'Teenage Caveman', 177, 'Arabic', 14, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (241, 'Unlikely Weapon, An', 273, 'French', 30, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (242, 'Hellzapoppin''', 509, 'Russian', 32, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (243, 'Two Lovers', 368, 'English', 21, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (244, 'Flannel Pajamas', 276, 'French', 17, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (245, 'Jack Strong', 287, 'Spanish', 18, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (246, 'Executive Suite', 624, 'Yiddish', 4, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (247, 'Garden of the Finzi-Continis, The (Giardino dei Finzi-Contini, Il)', 832, 'Arabic', 10, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (248, 'Wolves', 563, 'English', 4, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (249, 'Girl on a Motorcycle, The', 675, 'English', 24, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (250, 'Lili', 696, 'Russian', 25, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (251, 'Stick', 707, 'French', 31, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (252, '200 Motels', 870, 'French', 16, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (253, 'Loft', 775, 'English', 9, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (254, 'Ten Minutes Older: The Cello', 143, 'Russian', 9, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (255, 'Touch of Evil', 881, 'Arabic', 17, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (256, 'Fine Madness, A', 984, 'Hebrew', 30, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (257, 'Chance Pe Dance', 393, 'Spanish', 33, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (258, 'Blood of Dracula', 601, 'Yiddish', 18, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (259, 'Red Hill', 7, 'Hebrew', 8, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (260, '9/11', 576, 'Arabic', 26, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (261, 'Me Without You', 708, 'English', 3, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (262, 'House on Sorority Row, The', 749, 'Arabic', 20, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (263, 'Casper''s Haunted Christmas', 329, 'Russian', 2, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (264, 'Hitchhiker''s Guide to the Galaxy, The', 171, 'Russian', 14, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (265, 'Bed & Breakfast: Love is a Happy Accident (Bed & Breakfast)', 167, 'Yiddish', 27, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (266, 'Jesse Stone: Thin Ice', 379, 'English', 3, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (267, 'Debt, The', 220, 'Yiddish', 11, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (268, 'All This, and Heaven Too', 22, 'English', 28, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (269, 'Quiet Ones, The', 173, 'Russian', 19, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (270, 'Nashville', 631, 'English', 33, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (271, 'Pitkä kuuma kesä', 647, 'Hebrew', 23, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (272, 'Walk All Over Me', 626, 'Hebrew', 1, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (273, 'Dukes of Hazzard, The', 779, 'Russian', 14, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (274, 'Adventures of Don Juan', 735, 'Russian', 25, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (275, 'Help Me, Eros (Bang bang wo ai shen)', 305, 'English', 33, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (276, 'Hard Word, The', 907, 'Arabic', 4, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (277, 'I Am Curious (Yellow) (Jag är nyfiken - en film i gult)', 39, 'Hebrew', 15, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (278, 'Grotesque (Gurotesuku)', 293, 'Yiddish', 32, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (279, 'Flow', 916, 'Russian', 8, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (280, 'Afstiros katallilo', 171, 'Yiddish', 23, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (281, 'Dr. Jekyll and Mr. Hyde', 166, 'English', 28, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (282, 'Seopyeonje', 471, 'Hebrew', 25, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (283, 'Suzanne''s Career (La carrière de Suzanne)', 52, 'Spanish', 14, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (284, 'Easy Come, Easy Go', 112, 'Yiddish', 27, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (285, 'Lourdes', 907, 'Hebrew', 16, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (286, 'Band''s Visit, The (Bikur Ha-Tizmoret)', 743, 'Arabic', 1, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (287, 'Oklahoma!', 146, 'Hebrew', 24, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (288, 'As You Like It', 163, 'English', 21, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (289, 'Perils of the Sentimental Swordsman', 786, 'Russian', 10, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (290, 'Pokémon the Movie: Black - Victini and Reshiram', 394, 'Hebrew', 23, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (291, 'Dark Corner, The', 32, 'Yiddish', 13, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (292, 'Digimon: The Movie', 77, 'English', 32, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (293, 'Last Ride', 147, 'Arabic', 29, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (294, 'Krabat', 747, 'Hebrew', 12, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (295, '20,000 Years in Sing Sing', 492, 'Yiddish', 25, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (296, 'Big Sur', 465, 'Yiddish', 20, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (297, 'Milky Way, The (Voie lactée, La)', 799, 'Russian', 30, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (298, 'Hostel: Part III ', 139, 'Hebrew', 30, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (299, 'To Each His Own', 317, 'Spanish', 5, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (300, 'OH in Ohio, The', 346, 'English', 16, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (301, 'Love, Marilyn', 332, 'Arabic', 24, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (302, 'Art of Flight, The', 320, 'Hebrew', 19, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (303, 'D-Day', 741, 'English', 11, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (304, 'Tales from the Crypt', 960, 'Hebrew', 7, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (305, 'Rudo y Cursi (Rough and Vulgar)', 534, 'French', 20, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (306, 'Jerk Theory, The', 969, 'Russian', 23, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (307, 'Miracle at Oxford (True Blue)', 645, 'Arabic', 25, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (308, 'Jim Thorpe -- All-American', 909, 'Russian', 33, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (309, 'Wayward Bus, The', 584, 'Russian', 22, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (310, 'Bride of Frankenstein, The (Bride of Frankenstein)', 814, 'Russian', 27, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (311, 'Wolf', 49, 'English', 19, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (312, 'Wild Hogs', 589, 'Arabic', 21, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (313, 'Kronos (a.k.a. Captain Kronos: Vampire Hunter)', 659, 'French', 27, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (314, 'Prince of Pennsylvania, The', 857, 'Hebrew', 21, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (315, 'Two Weeks in September', 10, 'Yiddish', 33, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (316, 'Detective Story', 776, 'Arabic', 8, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (317, 'Operation Mad Ball', 825, 'Hebrew', 24, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (318, 'Fire Within, The (Feu follet, Le)', 505, 'Hebrew', 20, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (319, 'American Mary', 748, 'Hebrew', 4, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (320, 'Gleaners & I, The (Les glaneurs et la glaneuse)', 194, 'Russian', 31, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (321, 'Love Bites', 357, 'French', 14, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (322, 'First Name: Carmen (Prénom Carmen)', 940, 'Yiddish', 14, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (323, 'The 39 Steps', 641, 'French', 8, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (324, 'Vera Cruz', 561, 'Hebrew', 15, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (325, 'Don Quixote (Don Quijote de Orson Welles)', 804, 'Spanish', 6, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (326, 'Cuenca Crime, The (Crimen de Cuenca, El)', 15, 'Hebrew', 5, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (327, 'Strategic Air Command', 339, 'French', 28, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (328, 'White Fang (Zanna Bianca)', 747, 'Arabic', 19, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (329, 'Happy Poet, The', 949, 'Hebrew', 33, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (330, 'Fear and Trembling (Stupeur et tremblements)', 874, 'Hebrew', 11, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (331, 'Heart of a Lion (Leijonasydän)', 214, 'English', 14, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (332, 'A Follower for Emily', 90, 'Yiddish', 16, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (333, '2012: Supernova', 431, 'Arabic', 7, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (334, 'Waitress', 537, 'Arabic', 4, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (335, 'God of Cookery (Sik san)', 689, 'French', 12, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (336, 'Abbott and Costello Go to Mars', 807, 'Yiddish', 18, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (337, 'Gold of Naples, The (L''oro di Napoli)', 251, 'Hebrew', 16, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (338, 'Bad Chicken', 739, 'Arabic', 2, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (339, 'Munich', 375, 'Yiddish', 28, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (340, 'Buddy Holly Story, The', 898, 'French', 27, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (341, 'Song of Freedom', 660, 'French', 21, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (342, 'Cockpit', 514, 'English', 8, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (343, 'One Trick Pony', 832, 'Russian', 5, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (344, 'O.C. and Stiggs', 704, 'French', 24, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (345, 'Rigor Mortis (Geung si)', 602, 'English', 30, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (346, 'Unholy Three, The', 163, 'Yiddish', 21, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (347, 'Jack-O', 549, 'Russian', 16, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (348, 'Chapter 27', 480, 'Arabic', 28, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (349, 'Impy''s Island', 347, 'Spanish', 14, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (350, 'Big Bad Mama II', 384, 'Arabic', 23, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (351, 'Robinson in Space', 556, 'Yiddish', 1, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (352, 'American Vagabond', 436, 'Russian', 19, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (353, 'Porgy and Bess', 480, 'French', 12, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (354, 'Wolves', 217, 'Arabic', 1, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (355, 'They Call Me Renegade', 72, 'Spanish', 24, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (356, 'Los Marziano', 741, 'Yiddish', 9, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (357, 'London Conspiracy', 134, 'English', 17, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (358, 'Simply Irresistible', 641, 'Hebrew', 21, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (359, 'Stepmom', 851, 'Arabic', 27, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (360, 'Hidden Face, The (La cara oculta)', 555, 'Russian', 18, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (361, 'Beefcake', 53, 'Spanish', 8, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (362, 'Mystery of the Yellow Room, The (Mystère de la chambre jaune, Le)', 745, 'Russian', 4, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (363, 'Holiday in Handcuffs', 963, 'Russian', 21, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (364, 'Jason Becker: Not Dead Yet', 385, 'Arabic', 5, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (365, 'Tsotsi', 432, 'French', 17, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (366, 'Death at a Funeral', 919, 'Arabic', 3, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (367, 'Goodbye Charlie', 412, 'Hebrew', 24, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (368, 'Hotel', 50, 'Russian', 15, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (369, 'Every Other Weekend (Un week-end sur deux)', 869, 'Russian', 7, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (370, 'The Burglar', 566, 'Russian', 31, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (371, 'Meet the Feebles', 662, 'Arabic', 20, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (372, 'Lord of the Flies', 44, 'Russian', 19, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (373, 'When in Rome', 835, 'French', 18, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (374, 'King Lear (Korol Lir)', 517, 'Yiddish', 26, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (375, 'Man of the House', 407, 'French', 30, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (376, 'Decampitated', 693, 'Spanish', 16, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (377, 'Suriyothai (a.k.a. Legend of Suriyothai, The)', 478, 'Hebrew', 4, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (378, 'Blade Runner', 27, 'Arabic', 25, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (379, 'Lifeguard', 358, 'French', 32, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (380, 'Endurance: Shackleton''s Legendary Antarctic Expedition, The', 567, 'French', 28, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (381, 'Confessions of a Teenage Drama Queen', 288, 'Russian', 5, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (382, 'Man of Aran', 66, 'French', 12, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (383, 'Spies Like Us', 898, 'Spanish', 11, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (384, 'Double Dhamaal', 227, 'Spanish', 15, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (385, 'Two Crimes (Dos crímenes)', 636, 'Hebrew', 28, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (386, 'Boat People (Tau ban no hoi)', 92, 'Yiddish', 25, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (387, 'Turtle Diary', 968, 'Spanish', 10, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (388, 'For Whom the Bell Tolls', 467, 'French', 13, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (389, 'On the Run', 718, 'Russian', 10, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (390, 'My Left Eye Sees Ghosts (Ngo joh aan gin diy gwai)', 664, 'Hebrew', 26, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (391, 'Late Night Shopping', 703, 'Russian', 18, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (392, 'Tracy Morgan: Black and Blue', 207, 'Spanish', 23, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (393, 'Birdsong (Cant dels ocells, El)', 932, 'Arabic', 25, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (394, 'Dark Wind, The', 353, 'Russian', 11, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (395, 'Fantomas', 801, 'English', 10, 8);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (396, 'Pride and Prejudice', 879, 'Russian', 3, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (397, 'The Butter Battle Book', 637, 'Russian', 20, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (398, 'Sand Sharks', 775, 'Hebrew', 16, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (399, 'Not Without My Daughter', 271, 'Yiddish', 16, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (400, 'RoboCop 2', 905, 'Arabic', 10, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (401, 'Betrayal', 657, 'Spanish', 30, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (402, 'Midnight Dancers (Sibak)', 470, 'English', 8, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (403, 'Fiend with the Electronic Brain (Blood of Ghastly Horror)', 667, 'Yiddish', 10, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (404, 'Bolt', 169, 'Arabic', 26, 1);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (405, 'Behind Enemy Lines', 35, 'Yiddish', 8, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (406, 'Skinwalkers', 302, 'Russian', 24, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (407, 'Arsène Lupin', 51, 'Russian', 9, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (408, 'Mechanic, The', 43, 'English', 33, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (409, 'Imitation of Life', 735, 'French', 15, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (410, 'Rogue Trader', 688, 'French', 6, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (411, 'Flying Swords of Dragon Gate, The (Long men fei jia)', 688, 'Spanish', 13, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (412, 'Parenthood', 9, 'Spanish', 15, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (413, 'Nothing But the Truth', 302, 'English', 20, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (414, 'Youngblood', 292, 'Yiddish', 27, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (415, 'Spring Subway', 564, 'Arabic', 11, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (416, 'Upstairs and Downstairs', 873, 'Spanish', 17, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (417, 'Escape to Athena', 886, 'Hebrew', 17, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (418, 'Mr. Skeffington', 467, 'French', 19, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (419, 'Harder They Fall, The', 481, 'Yiddish', 27, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (420, 'Don Quixote (Don Quijote de Orson Welles)', 885, 'English', 33, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (421, 'Street Fighter: Assassin''s Fist', 490, 'French', 26, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (422, 'Raze', 325, 'English', 5, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (423, 'Human Nature', 772, 'Hebrew', 16, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (424, 'Mad Max Beyond Thunderdome', 242, 'Hebrew', 27, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (425, 'Comedy of Innocence (Comédie de l''innocence)', 702, 'Hebrew', 26, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (426, 'How to Live Forever', 312, 'Russian', 14, 25);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (427, 'Besieged (a.k.a. L'' Assedio)', 413, 'Russian', 23, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (428, 'Life and Death of Colonel Blimp, The', 359, 'French', 25, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (429, 'Young Guns', 103, 'Arabic', 25, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (430, 'Satan''s Sword (Daibosatsu tôge)', 15, 'English', 14, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (431, 'Robin Williams: Weapons of Self Destruction', 772, 'Russian', 25, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (432, 'The Wind in the Willows', 400, 'Russian', 8, 19);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (433, 'Batman', 410, 'Hebrew', 8, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (434, 'J. Gang Meets Dynamite Harry, The (Jönssonligan & DynamitHarry)', 797, 'French', 5, 32);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (435, 'Closet, The (Placard, Le)', 913, 'French', 13, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (436, '10', 399, 'Spanish', 3, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (437, 'Invincible Iron Man, The', 18, 'French', 12, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (438, 'Snails, The (Escargots, Les)', 588, 'French', 23, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (439, 'In a Town This Size', 24, 'Arabic', 17, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (440, 'The Returned', 199, 'Yiddish', 12, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (441, 'Johnny Guitar', 916, 'French', 22, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (442, 'Wedding Planner, The', 985, 'Arabic', 31, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (443, 'Brick Lane', 603, 'Yiddish', 3, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (444, 'Jason Goes to Hell: The Final Friday', 577, 'Yiddish', 2, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (445, 'Raise the Red Lantern (Da hong deng long gao gao gua)', 514, 'Yiddish', 7, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (446, 'Scum', 295, 'Arabic', 11, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (447, 'Love Streams', 504, 'English', 9, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (448, 'Chase, The', 376, 'Hebrew', 8, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (449, 'Stuart: A Life Backward', 29, 'French', 11, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (450, 'Arizona Raiders', 374, 'Arabic', 18, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (451, 'Nights in Rodanthe', 193, 'Yiddish', 23, 15);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (452, 'Jean Gentil', 435, 'Yiddish', 19, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (453, 'Bombay Talkie', 16, 'English', 9, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (454, 'Deck the Halls', 592, 'French', 22, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (455, 'Dragon Seed', 117, 'Spanish', 23, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (456, 'Frozen', 433, 'Hebrew', 28, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (457, 'Mutants', 142, 'English', 19, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (458, 'Making a Killing: The Untold Story of Psychotropic Drugging', 750, 'English', 20, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (459, 'Man of Tai Chi', 453, 'Hebrew', 12, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (460, 'Knock on Any Door', 933, 'Arabic', 19, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (461, 'Swann in Love (Un amour de Swann)', 757, 'Yiddish', 12, 26);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (462, 'Flypaper', 990, 'Spanish', 12, 23);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (463, 'This Is England', 172, 'Russian', 13, 27);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (464, 'Story of Seabiscuit, The', 760, 'Spanish', 23, 11);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (465, 'Mister Buddwing', 297, 'English', 17, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (466, 'A Year Along the Abandoned Road', 940, 'English', 23, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (467, 'Do Fish Do It? (Fickende Fische)', 866, 'Russian', 14, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (468, 'Three Brave Men', 290, 'Yiddish', 4, 16);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (469, 'Rampo (a.k.a. The Mystery of Rampo)', 430, 'Russian', 16, 21);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (470, 'Love and Death on Long Island', 562, 'Hebrew', 12, 7);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (471, 'Sun Also Rises, The (Tai yang zhao chang sheng qi)', 510, 'Russian', 8, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (472, 'Firestarter', 809, 'Yiddish', 6, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (473, 'Schultze Gets the Blues', 187, 'Russian', 11, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (474, 'Sexo, Amor e Traição', 310, 'Yiddish', 24, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (475, 'Finger, The (Dedo, El)', 939, 'Spanish', 8, 29);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (476, 'Bongwater', 58, 'Russian', 31, 22);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (477, 'Godzilla and Mothra: The Battle for Earth (Gojira vs. Mosura)', 826, 'Yiddish', 3, 17);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (478, 'Muppet Family Christmas, A', 326, 'Hebrew', 22, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (479, 'Walk Like a Man', 229, 'Russian', 30, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (480, 'His Girl Friday', 744, 'Arabic', 29, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (481, 'Barefoot Executive, The', 754, 'French', 23, 6);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (482, 'We All Loved Each Other So Much (C''eravamo tanto amati)', 665, 'Russian', 19, 3);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (483, 'Twelve O''Clock High', 49, 'Russian', 28, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (484, 'Theatre of Blood', 677, 'Arabic', 29, 20);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (485, 'Fill the Void (Lemale et ha''halal)', 514, 'Yiddish', 7, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (486, 'Little Miss Sunshine', 388, 'French', 29, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (487, 'Borrower, The', 245, 'Hebrew', 5, 12);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (488, 'Don', 437, 'Arabic', 3, 4);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (489, 'Something Borrowed', 973, 'Spanish', 11, 9);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (490, 'Man of No Importance, A', 78, 'Yiddish', 30, 28);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (491, 'America: Imagine the World Without Her', 814, 'Russian', 24, 13);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (492, 'House', 573, 'Hebrew', 4, 24);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (493, 'Tombstone', 461, 'Arabic', 3, 18);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (494, 'Volver', 416, 'Hebrew', 25, 31);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (495, 'Turner & Hooch', 505, 'English', 32, 5);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (496, 'Attack, The', 100, 'French', 22, 10);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (497, 'Avengers, The', 628, 'Hebrew', 16, 30);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (498, 'Pokémon: The First Movie', 757, 'Arabic', 33, 14);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (499, 'Yamla Pagla Deewana 2', 484, 'French', 25, 2);
insert into book (bookId, title, pages, bookLanguage, categoryId, publisherId) values (500, 'Killing of John Lennon, The', 402, 'French', 27, 1);
HTTP/1.1 500 Internal Server Error

