insert into play (playId, playName, categoryId, publisherId) values (1, '13 Dead End Drive', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (2, '1313 Dead End Drive', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (3, '18XX', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (4, '221B Baker Street: The Master Detective Game', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (5, '30 Seconds', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (6, '500 rum', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (7, 'A Feast for Odin', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (8, 'A Game of War', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (9, 'Abalone', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (10, 'About Time', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (11, 'Acquire', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (12, 'Acronymble', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (13, 'Afrikan tähti', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (14, 'Agon', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (15, 'Agricola', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (16, 'Air Charter', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (17, 'Aksharit', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (18, 'Aladdin''s Dragons', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (19, 'Alhambra', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (20, 'Alias', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (21, 'American Megafauna', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (22, 'Amun-Re', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (23, 'Android: Netrunner', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (24, 'Anti-Monopoly', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (25, 'Apples to Apples', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (26, 'Arimaa', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (27, 'Arkham Horror', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (28, 'Articulate!', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (29, 'Asalto', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (30, 'Attack!', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (31, 'Auf Achse', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (32, 'Australia', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (33, 'Ave Caesar', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (34, 'Axis & Allies', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (35, 'Azul', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (36, 'Backgammon', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (37, 'Bailout! The Game', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (38, 'Balderdash', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (39, 'Bang!', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (40, 'Barbarossa', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (41, 'Battle Sheep', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (42, 'BattleLore', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (43, 'Battleship', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (44, 'Battlestar Galactica', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (45, 'Beggar-my-neighbour', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (46, 'Betrayal at House on the Hill', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (47, 'Bezzerwizzer', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (48, 'Blackjack', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (49, 'Blankety Blank', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (50, 'Blockade', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (51, 'Blokus', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (52, 'Blood Bowl', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (53, 'Blood Feud in New York', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (54, 'Blood Rage', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (55, 'Blue Max', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (56, 'Bonkers!', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (57, 'Bookchase', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (58, 'Brain Chain', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (59, 'Briscola', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (60, 'Buccaneer', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (61, 'Bul', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (62, 'Camel Up', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (63, 'Camelot', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (64, 'Canasta', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (65, 'Candy Land', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (66, 'Can''t Stop', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (67, 'Capitol', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (68, 'Carcassonne', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (69, 'Careers', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (70, 'Caribbean', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (71, 'Cartagena', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (72, 'Castle Risk', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (73, 'Catan (The Settlers of Catan)', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (74, 'Caylus', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (75, 'Chaturanga (Indian chess)', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (76, 'Cheat', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (77, 'Checkers', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (78, 'Chess', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (79, 'Chinese checkers (Sternhalma)', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (80, 'Chowka bhara', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (81, 'Chromino', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (82, 'CirKis', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (83, 'Civilization', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (84, 'Clans', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (85, 'Clue Jr.: Case of the Missing Pet', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (86, 'Clue/Cluedo', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (87, 'Codenames', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (88, 'Coin Hopping—Washington D.C.', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (89, 'Colt Express', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (90, 'Commands & Colors: Ancients', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (91, 'Concept', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (92, 'Connect Four', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (93, 'Connect6', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (94, 'Conspiracy', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (95, 'Continuo', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (96, 'Contract bridge', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (97, 'Coppit', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (98, 'Cosmic Encounter', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (99, 'Cranium', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (100, 'Crazy Eights', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (101, 'Cribbage', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (102, 'Cross and circle game', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (103, 'Crosstrack', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (104, 'Daldøs', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (105, 'Dark Tower', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (106, 'Dead of Winter: A Cross Roads Game', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (107, 'Diamant', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (108, 'Diamond', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (109, 'Diceball!', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (110, 'Die Macher', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (111, 'Diplomacy', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (112, 'Dixit', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (113, 'Djambi', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (114, 'Dominion', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (115, 'Don''t Miss the Boat', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (116, 'Don''t Quote Me', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (117, 'Doom: The Boardgame', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (118, 'Dorn', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (119, 'Doublets', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (120, 'Downfall', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (121, 'Draughts', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (122, 'Drunter und Drüber', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (123, 'Dune', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (124, 'Dungeons & Dragons', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (125, 'Dutch Blitz', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (126, 'DVONN', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (127, 'Eclipse: New Dawn for the Galaxy', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (128, 'Egyptian Ratscrew', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (129, 'El Grande', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (130, 'Elfenland', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (131, 'Enchanted Forest', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (132, 'English Game', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (133, 'Entdecker', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (134, 'Escape from Atlantis', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (135, 'Everdell', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (136, 'Exploding Kittens', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (137, 'Fanorona', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (138, 'Fictionary', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (139, 'Figure It Out', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (140, 'Finance', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (141, 'Fireball Island', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (142, 'Focus', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (143, 'Fresco', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (144, 'Game For Fame', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (145, 'Game of the Generals', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (146, 'Ghettopoly', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (147, 'Ghosts', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (148, 'Gift Trap', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (149, 'Giganten', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (150, 'Gin rummy', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (151, 'GIPF', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (152, 'Girl Talk', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (153, 'Glückshaus', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (154, 'Go', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (155, 'Go Fish', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (156, 'Gobblet', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (157, 'Gomoku', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (158, 'Gong Zhu', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (159, 'Go-Stop', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (160, 'GridIron Master', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (161, 'Guess Who?', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (162, 'Halma', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (163, 'Hare and Hounds', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (164, 'Hearts', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (165, 'Heroscape', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (166, 'Hex', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (167, 'Hey, That''s My Fish!', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (168, 'Hijara', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (169, 'History of the World', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (170, 'Hoity Toity', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (171, 'Hooop!', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (172, 'Hotel', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (173, 'Hounds and Jackals', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (174, 'Hūsker Dū?', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (175, 'I''m the Boss!', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (176, 'Imhotep', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (177, 'Imperial', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (178, 'Indigo', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (179, 'Ingenious', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (180, 'Inkan aarre', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (181, 'Irish', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (182, 'Jacquet', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (183, 'Jaipur', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (184, 'Janggi (Korean chess)', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (185, 'Jass', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (186, 'Java', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (187, 'Jenga', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (188, 'John Company', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (189, 'Journey Through Europe', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (190, 'Junta', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (191, 'Kalah', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (192, 'Kamisado', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (193, 'Karuba', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (194, 'Keltis', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (195, 'Kemps', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (196, 'Khet', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (197, 'Kill Doctor Lucky', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (198, 'King of Tokyo', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (199, 'King Oil', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (200, 'Kingdomino', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (201, 'Kingdoms', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (202, 'Knock-out whist', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (203, 'Labyrinth', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (204, 'Landslide', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (205, 'Las Vegas', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (206, 'Le Havre', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (207, 'Liubo', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (208, 'Lords of Waterdeep', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (209, 'Lost Cities', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (210, 'Löwenherz', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (211, 'Luck of the Draw', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (212, 'Ludo', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (213, 'Mad Gab', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (214, 'Mahjong', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (215, 'Makruk (Thai chess)', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (216, 'Malefiz', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (217, 'Mall Madness', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (218, 'Manhattan', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (219, 'Mastermind', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (220, 'Masterpiece', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (221, 'Matching game', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (222, 'Mau-Mau', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (223, 'Medici', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (224, 'Medina', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (225, 'Memory', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (226, 'Mensch ärgere Dich nicht', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (227, 'Merchant of Venus', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (228, 'Metro', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (229, 'Mexica', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (230, 'Mikado', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (231, 'Mine a Million', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (232, 'Modern Art', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (233, 'Monopoly', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (234, 'Monopoly Deal', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (235, 'Mutant Meeples', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (236, 'Near and Far', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (237, 'Nerts', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (238, 'Niagara', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (239, 'Nine men''s morris', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (240, 'Okey', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (241, 'Old maid', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (242, 'Omega Virus', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (243, 'One-card', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (244, 'Onyx', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (245, 'Operation', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (246, 'Ouija', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (247, 'Ouk-Khmer (Cambodian chess)', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (248, 'Outrage!', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (249, 'Oware', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (250, 'Pack & Stack', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (251, 'Pank-a-Squith', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (252, 'Parcheesi', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (253, 'Parqués', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (254, 'Patience', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (255, 'Pay Day', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (256, 'Personal Preference', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (257, 'Phase 10', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (258, 'Pictionary', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (259, 'Pinochle', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (260, 'Pirate''s Cove', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (261, 'Plateau', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (262, 'Poker', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (263, 'Poleconomy', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (264, 'Power Grid', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (265, 'Primordial Soup', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (266, 'Probe', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (267, 'Puerto Rico', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (268, 'PÜNCT', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (269, 'Puzzle', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (270, 'Qin', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (271, 'Quarto', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (272, 'Quoridor', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (273, 'Qwirkle', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (274, 'Qwirkle', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (275, 'Ra', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (276, 'Rack-O', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (277, 'Rail Baron', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (278, 'Railway Rivals', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (279, 'Reversi (Othello)', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (280, 'Ricochet Robots', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (281, 'Risk', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (282, 'Rithmomachy', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (283, 'Rivers, Roads & Rails', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (284, 'RoboRally', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (285, 'RSVP', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (286, 'Rummikub', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (287, 'Rummoli', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (288, 'Rummoli', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (289, 'Rummy', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (290, 'Saboteur', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (291, 'Sáhkku', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (292, 'Saint Petersburg', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (293, 'Samurai', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (294, 'San Marco', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (295, 'Santorini', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (296, 'Scattergories', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (297, 'Scene It?', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (298, 'Schnapsen', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (299, 'Scotland Yard', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (300, 'Scoundrels of Skullport', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (301, 'Scrabble', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (302, 'Scythe', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (303, 'Sector 41', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (304, 'Senet', 4, 6);
insert into play (playId, playName, categoryId, publisherId) values (305, 'Sequence', 1, 2);
insert into play (playId, playName, categoryId, publisherId) values (306, 'Set', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (307, 'Shadow Hunters', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (308, 'Shadows over Camelot', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (309, 'Shatar (Mongolian chess)', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (310, 'Shatranj (Persian chess)', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (311, 'Shengguan Tu', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (312, 'Sherlock Holmes: Consulting Detective', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (313, 'Shichi Narabe', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (314, 'Shogi (Japanese chess)', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (315, 'Shogun/Samurai Swords', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (316, 'Simon', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (317, 'Sittuyin (Burmese chess)', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (318, 'Skat', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (319, 'Skip-Bo', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (320, 'Skip-Bo', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (321, 'Skirrid', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (322, 'Slapjack', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (323, 'Sleeping Queens', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (324, 'Small World', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (325, 'Snakes and Ladders', 5, 2);
insert into play (playId, playName, categoryId, publisherId) values (326, 'Snap', 3, 1);
insert into play (playId, playName, categoryId, publisherId) values (327, 'Snip-snap-snorum', 4, 3);
insert into play (playId, playName, categoryId, publisherId) values (328, 'Solarquest', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (329, 'Sorry!', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (330, 'Space Hulk', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (331, 'Spades', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (332, 'Splendor', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (333, 'Spoons', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (334, 'Spy Alley', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (335, 'Squatter', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (336, 'Star Wars Epic Duels', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (337, 'Star Wars Tactics', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (338, 'Star Wars: X-Wing Miniatures Game', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (339, 'StarCraft: The Board Game', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (340, 'Stock Ticker', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (341, 'Strange Synergy', 4, 4);
insert into play (playId, playName, categoryId, publisherId) values (342, 'Stratego', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (343, 'Suffragetto', 2, 2);
insert into play (playId, playName, categoryId, publisherId) values (344, 'Sugoroku', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (345, 'Summit', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (346, 'Summoner Wars (Second Edition)', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (347, 'Ta Yü', 2, 3);
insert into play (playId, playName, categoryId, publisherId) values (348, 'Tâb', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (349, 'Tafl (Tablut)', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (350, 'Taj Mahal', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (351, 'Tak', 1, 3);
insert into play (playId, playName, categoryId, publisherId) values (352, 'Take It Easy', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (353, 'Take the Galaxy', 1, 1);
insert into play (playId, playName, categoryId, publisherId) values (354, 'Tantrix', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (355, 'TEG', 3, 6);
insert into play (playId, playName, categoryId, publisherId) values (356, 'Terakh', 5, 6);
insert into play (playId, playName, categoryId, publisherId) values (357, 'Terra Mystica', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (358, 'Terraforming Mars', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (359, 'The Farming Game', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (360, 'The Game of Life', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (361, 'The Great Train Robbery', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (362, 'The Great Train Robbery', 4, 5);
insert into play (playId, playName, categoryId, publisherId) values (363, 'The LOGO Board Game', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (364, 'The London Game', 3, 3);
insert into play (playId, playName, categoryId, publisherId) values (365, 'The Mad Magazine Game', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (366, 'The Magic Labyrinth', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (367, 'The Princes of Florence', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (368, 'The Quest of the Philosopher''s Stone', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (369, 'Three thirteen', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (370, 'Through the Ages: A Story of Civilization', 3, 4);
insert into play (playId, playName, categoryId, publisherId) values (371, 'Through the Desert', 4, 2);
insert into play (playId, playName, categoryId, publisherId) values (372, 'Thurn and Taxis', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (373, 'Ticket to Ride', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (374, 'Tigris and Euphrates', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (375, 'Tikal', 5, 4);
insert into play (playId, playName, categoryId, publisherId) values (376, 'Timberland', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (377, 'Time''s Up!', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (378, 'Titan', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (379, 'Top Secret Spies', 2, 4);
insert into play (playId, playName, categoryId, publisherId) values (380, 'Torres', 4, 1);
insert into play (playId, playName, categoryId, publisherId) values (381, 'Totopoly', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (382, 'Tracks to Telluride', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (383, 'TransAmerica', 2, 5);
insert into play (playId, playName, categoryId, publisherId) values (384, 'Travel Go', 3, 5);
insert into play (playId, playName, categoryId, publisherId) values (385, 'Trick-taking game', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (386, 'Tri-nim', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (387, 'Trivial Pursuit', 5, 5);
insert into play (playId, playName, categoryId, publisherId) values (388, 'Trouble', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (389, 'Tsuro', 1, 5);
insert into play (playId, playName, categoryId, publisherId) values (390, 'Tsuro of the Seas', 1, 4);
insert into play (playId, playName, categoryId, publisherId) values (391, 'Twilight Imperium', 5, 1);
insert into play (playId, playName, categoryId, publisherId) values (392, 'Twilight Struggle: The Cold War, 1945–1989', 2, 6);
insert into play (playId, playName, categoryId, publisherId) values (393, 'Ubongo', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (394, 'Uno', 5, 3);
insert into play (playId, playName, categoryId, publisherId) values (395, 'Uno Flip!', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (396, 'Upwords', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (397, 'Vanished Planet', 2, 1);
insert into play (playId, playName, categoryId, publisherId) values (398, 'Verquere', 3, 2);
insert into play (playId, playName, categoryId, publisherId) values (399, 'Vinci', 1, 6);
insert into play (playId, playName, categoryId, publisherId) values (400, 'War', 3, 4);